CREATE TABLE pitching_gamelogs (
    player_id TEXT NOT NULL,
    game_id TEXT NOT NULL,
    gs INTEGER,
    cg INTEGER,
    sho INTEGER,
    gf INTEGER,
    ipouts INTEGER,
    ab INTEGER,
    bf INTEGER,
    h INTEGER,
    r INTEGER,
    er INTEGER,
    hr INTEGER,
    bb INTEGER,
    ibb INTEGER,
    so INTEGER,
    wp INTEGER,
    bk INTEGER,
    hbp INTEGER,
    gb INTEGER,
    fb INTEGER,
    p INTEGER,
    s INTEGER,
    decision TEXT
)
