CREATE TABLE people (
    key_person TEXT NOT NULL,
    key_uuid TEXT NOT NULL,
    key_mlbam INTEGER,
    key_retro TEXT,
    key_bbref TEXT,
    key_bbref_minors TEXT,
    key_fangraphs TEXT,
    key_npb TEXT,
    key_sr_nfl TEXT,
    key_sr_nba TEXT,
    key_sr_nhl TEXT,
    key_wikidata TEXT,
    name_last TEXT,
    name_first TEXT,
    name_given TEXT,
    name_suffix TEXT,
    name_matrilineal TEXT,
    name_nick TEXT,
    birth_year INTEGER,
    birth_month INTEGER,
    birth_day INTEGER,
    death_year INTEGER,
    death_month INTEGER,
    death_day INTEGER,
    pro_played_first INTEGER,
    pro_played_last INTEGER,
    mlb_played_first INTEGER,
    mlb_played_last INTEGER,
    col_played_first INTEGER,
    col_played_last INTEGER,
    pro_managed_first INTEGER,
    pro_managed_last INTEGER,
    mlb_managed_first INTEGER,
    mlb_managed_last INTEGER,
    col_managed_first INTEGER,
    col_managed_last INTEGER,
    pro_umpired_first INTEGER,
    pro_umpired_last INTEGER,
    mlb_umpired_first INTEGER,
    mlb_umpired_last INTEGER
)
