CREATE TABLE batting_gamelogs (
    player_id TEXT NOT NULL,
    game_id TEXT NOT NULL,
    team_id TEXT NOT NULL,
    career_game INTEGER,
    season_game INTEGER,
    team_game INTEGER,
    pa INTEGER,
    ab INTEGER,
    r INTEGER,
    h INTEGER,
    d INTEGER,
    t INTEGER,
    hr INTEGER,
    rbi INTEGER,
    rbi2out INTEGER,
    bb INTEGER,
    ibb INTEGER,
    so INTEGER,
    gidp INTEGER,
    hbp INTEGER,
    sh INTEGER,
    sf INTEGER,
    sb INTEGER,
    cs INTEGER,
    bavg REAL,
    obp REAL,
    slg REAL,
    woba REAL,
    babip REAL,
    pos TEXT
)
